### ISSUE TITLE
[BUG] Plugin not loading Spigot 1.19.3

### ISSUE THREAD

**Issue by Lennord** [TonimatasMCDEV/PerWorldCommands#4]
Hello, following your update today, when I launch my Spigot 1.19.3 server I have this error and following this, the plugin does not load and is not in the list of plugins ( ps: I only have your plugin installed, nothing else...).

> [18:46:16] [Server thread/ERROR]: Could not load 'plugins\PerWorldCommands-1.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `net.tonimatasmc.perworldcommands.PerWorldCommands'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:69) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3615-Spigot-61bffe0-eecb4c0]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3615-Spigot-61bffe0-eecb4c0]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3615-Spigot-61bffe0-eecb4c0]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3615-Spigot-61bffe0-eecb4c0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.tonimatasmc.perworldcommands.PerWorldCommands
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 8 more

**Comment by TonimatasDEV** [comment]
Fixed

**Comment by Lennord** [comment]
okay thank you so much.

**Comment by TonimatasDEV** [comment]
> okay thank you so much.

https://modrinth.com/plugin/perworldcommands/version/1.1.1
